CREATE TABLE USER
(
    userId      BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '사용자 ID',
    email       VARCHAR(100)          COMMENT '이메일',
    userName    VARCHAR(100) NOT NULL COMMENT '사용자 명',
    createAt    TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
    updateAt    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일'
);

CREATE TABLE SCHEDULE
(
    scheduleId  BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '일정 ID',
    userId      BIGINT       NOT NULL COMMENT '사용자 ID',
    userName    VARCHAR(100) NOT NULL COMMENT '사용자 명',
    toDoContent VARCHAR(100) NOT NULL COMMENT '할일',
    createAt    TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
    updateAt    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',

    FOREIGN KEY (userId) REFERENCES USER (userId) -- USER 테이블의 userId 참조
)


