CREATE TABLE SCHEDULE
(
    scheduleId  BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '일정 ID',
    password    VARCHAR(100) NOT NULL COMMENT '비밀번호',
    userName    VARCHAR(100) NOT NULL COMMENT '사용자 명',
    toDoContent VARCHAR(100) NOT NULL COMMENT '할일',
    createAt    TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
    updateAt    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일'
);


